//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestellingProtuct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BestellingProtuct()
        {
            this.Producten = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public short Aantal { get; set; }
        public string Totaal { get; set; }
        public int BestellingId { get; set; }
        public int ProductId { get; set; }
    
        public virtual Bestelling Bestelling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Producten { get; set; }
    }
}
