//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestelling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bestelling()
        {
            this.BestellingPrutucten = new HashSet<BestellingProtuct>();
        }
    
        public int Id { get; set; }
        public string Tafel { get; set; }
        public decimal Totaal { get; set; }
        public bool IsBezorcht { get; set; }
        public string IsBezorchtTS { get; set; }
        public bool IsKlaarKeuken { get; set; }
        public string IsKlaarKeukenTS { get; set; }
        public bool IsPrinted { get; set; }
        public string TS { get; set; }
        public int DagId { get; set; }
        public Nullable<int> OpdienerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BestellingProtuct> BestellingPrutucten { get; set; }
        public virtual Dag Dag { get; set; }
        public virtual Opdiener Opdiener { get; set; }
    }
}
