//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bier : Product
    {
        public decimal Alcohol { get; set; }
        public decimal Inhoud { get; set; }
        public int Aantal { get; set; }
        public int BierTypeId { get; set; }
        public int BierGistingId { get; set; }
        public int BrouwerijId { get; set; }
    
        public virtual BierType BierType { get; set; }
        public virtual BierGisting BierGisting { get; set; }
        public virtual Brouwerij Brouwerij { get; set; }
    }
}
