//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BMSModelContainer : DbContext
    {
        public BMSModelContainer()
            : base("name=BMSModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bierkroeg> Bierkroegen { get; set; }
        public virtual DbSet<Dag> Dagen { get; set; }
        public virtual DbSet<Opdiener> Opdieners { get; set; }
        public virtual DbSet<Bestelling> Bestellings { get; set; }
        public virtual DbSet<BestellingProtuct> BestellingProtucts { get; set; }
        public virtual DbSet<ProductCategorie> ProductCategories { get; set; }
        public virtual DbSet<BierType> BierTypes { get; set; }
        public virtual DbSet<BierGisting> BierGistings { get; set; }
        public virtual DbSet<Brouwerij> Brouwerijs { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    }
}
