//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dag()
        {
            this.Bestellingen = new HashSet<Bestelling>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public Nullable<System.DateTime> TS { get; set; }
        public int BierkroegId { get; set; }
    
        public virtual Bierkroeg Bierkroeg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestelling> Bestellingen { get; set; }
    }
}
