//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Bierkroegen = new HashSet<Bierkroeg>();
            this.BestellingProtucten = new HashSet<BestellingProtuct>();
        }
    
        public int Id { get; set; }
        public string ProductNaam { get; set; }
        public decimal Prijs { get; set; }
        public string Beschrijving { get; set; }
        public bool InVoorraad { get; set; }
        public byte[] IMG { get; set; }
        public int ProductCategorieId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bierkroeg> Bierkroegen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BestellingProtuct> BestellingProtucten { get; set; }
        public virtual ProductCategorie ProductCategorie { get; set; }
    }
}
